version: '3.4'

networks:
    backend:
        
services:

    n5challengedockerdemodb:
        container_name: n5challengedockerdemodb
        image: mcr.microsoft.com/mssql/server:2022-latest
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=yourStrong(!)Password 
        networks:
        - backend
        ports:
        - 1433:1433
        
    n5challengedockerdemo:
            image: ${DOCKER_REGISTRY-}n5challengedockerdemo
            build:
              context: .
              dockerfile: N5ChallengeDockerDemo/Dockerfile
            networks:
            - backend
            ports:
            - 8002:8002                
            environment:
            - DB_HOST=n5challengedockerdemodb
            - DB_NAME=N5demo
            - DB_SA_PASSWORD=yourStrong(!)Password
            - ELASTIC_URL=https://localhost:9200/
            - ELASTIC_INDEX=elasticsearch

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
        environment:
            - "discovery.type=single-node"
        networks:
        - backend
        ports:
        - 9200:9200    
    
    zookeeper:
        image: confluentinc/cp-zookeeper:latest
        environment:
          ZOOKEEPER_CLIENT_PORT: 2181
          ZOOKEEPER_TICK_TIME: 2000

    kafka:
        image: confluentinc/cp-kafka
        depends_on:
          - zookeeper
        networks:
          - backend
        ports:
          - 9092:9092
        environment:
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    
    

